{
  "hash": "347f4cc7e93a4d0aefd9ce7d906e48ec",
  "result": {
    "engine": "knitr",
    "markdown": "# Auswerten: Berichten von Statistiken {#sec-reportstats}\n\n\n\n## Lernsteuerung\n\n\n### Lernziele\n\n\n- Sie können Ihre Forschungfrage mit Methoden der Inferenzstatistik nach Bayes auswerten.\n\n\n\n\n### Position im Lernpfad\n\nSie befinden sich im Abschnitt \"Auswertung\" in @fig-ueberblick.\nBehalten Sie Ihren Fortschritt im Projektplan im Blick, s. @fig-projektplan.\n\n\n### tl;dr\n\nIn diesem Kapitel wird folgende Frage beantwortet: \"Wie man die Ergebnisse einer Bayes-Analyse berichtet\"\n\n\n### Benötigte R-Pakete\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(easystats)\nlibrary(rstanarm)\nlibrary(gt)  # optional\nlibrary(gtsummary)  # optional\n```\n:::\n\n\n\n\n\n\n\n## Warum das Berichten (Ihrer Analyse) wichtig ist\n\n\nStatistische Analysen können komplex und schwierig zu verstehen sein.^[Das war Ihnen noch nicht aufgefallen? Ach so.]\nDie Versuchung ist daher immer gegeben, beim Berichten einer Analyse wichtige Aspekte\nunerwähnt oder unerklärt zu lassen.\nLässt man aber wichtige Informationen aus, steigt die Gefahr,\ndass die Analyse nicht nachvollziehbar ist.\nAm schönsten ist dieses Problem im [Cartoon mit den zwei Wissenschaftlern von einer Tafel (von Sidney Harris)](http://www.sciencecartoonsplus.com/pages/gallery.php) dargestellt.\n\n\n:::{.callout-important}\nStellen Sie sicher, dass Ihre Analyse nachvollziehbar ist.\nAndere Personen sollten Ihre Analyse auch ausführen können.\nDaher ist es wichtig, dass Sie Ihre Analyse zu Ihrer Studie einreichen (außerdem auch die Daten und Ihr Data-Dictionary).$\\square$\n:::\n\n## Prinzipien der Berichtlegung (von Bayes-Statistik)\n\nIm Folgenden sind einige Grundlagen des Berichtens von Statistiken dargestellt.\nZwar wird in einigen Teilen auf die Bayes-Methode abgestellt, \naber viele Teile gelten für alle statistischen Analysen.\nDabei sei hinzugefügt, dass Statistik, so nüchtern sie den geneigten Studenis auch erscheinen mag,\ndurchaus Eitel- und Partikularitäten aufweist:\nNicht jeder Autor oder Dozent oder jede Richtlinie gibt die gleichen Anweisungen oder Empfehlungen!\nDie folgenden Hinweise entsprechen der (aktuellen, sich durchaus im Lauf der Zeit ändernden) Sicht dieses Dozenten.\n\n\nDas *erste* Prinzip des Berichtlegens lautet \"so viel wie nötig, aber so wenig wie möglich\".\nMan will die Lesis nicht überfrachten, aber alle nötigen Informationen übermitteln.\nDas *zweite* Prinzip lautet, dass man die Informationen am rechten Ort vermittelt.\nSo wird ei Lesi die Erklärung der Zusammensetzung der Stichprobe nicht im Diskussionsteil vermuten \nund sich zu Recht wundern, im Methodenteil nichts zur Stichprobe zu finden.\nDas *dritte* Prinzip lautet, dass man priorisiert. \nWichtiges in den Hauptteil, Details in den Anhang (bzw. in ergänzende Datein, \"supplementary files\").\nDetaillreiche Statistiken berichtet man eher in Tabellen;\ngeht es um einen Überblick, bietet sich häufig ein Diagramm an.\nBerichtet man im Text, so schreibt man auf \"gut Deutsch\" die Aussage in den Satz,\nund die Zahlen eher in Klammern dahinter.\nDas *vierte* Prinzip lautet, konsistent zu sein. \nEs gibt viele Wege nach Rom, bzw. viele Ansätze, nützlich und effektiv -\nmithin \"richtig\" - zu berichten. Wichtiger als die Wahl einer bestimmten Art und Weise,\nist es, konsistent zu sein, ähnlich wie beim Zitieren.\nDas *fünfte* Prinzip, könnte man sagen,  ist so selbstverständlich,\ndass es keiner Erwähnung bedarfe, aber die Realität lehrt uns leider mitunter das Gegenteil.\nEs lautet Lauterkeit oder Rechtschaffenheit.\nKennzahlen bewusst falsch zu berichten rangiert irgendwo zwischen Straftat und beruflichem Fehlverhalten,\nje nach Kontext und kann harte Bestrafung verdienen.\nGängiger sicherlich sind subtilere Arten, dieses Prinzip zu verletzen.\nDazu ist als erstes das selektive Berichten zu nennen: Unliebsame Befunde werden verschwiegen,\nhypothesenkonforme hingegen nach vorne gestellt.\nDas ist zwar dann nicht gelogen aber die Irreführung wird bewusst in Kauf genommen.\n\nDie *gute* Nachricht für alle Studentis: Es gibt für Sie keinen Anreiz,\ndie Ergebnisse \"aufzuhübschen\" (im Gegensatz zu Berufswissenschaftlis). \nIhre Note wird nicht daran gemessen, ob Sie einen neuen [Expoplaneten](https://de.wikipedia.org/wiki/Exoplanet)\nentdecken, \noder sonstige \"starke\" Ergebnisse aufweisen können.\nNein! Unklare, nicht-bestätigende oder unerwartete Ergebnisse sind genauso gut -\nauch wissenschaftlich übrigens haben sie die gleiche Daseinsberechtigung,\nwie die Ergebnisse, die im \"Journal of Flashy Results\" für Presseberichte sorgen.\nFür ihre Note ist es unerheblich, wie \"signifikant\", \"effektstark\", \"präzise\" oder \"hypothesenkonform\"\nihre Ergebnisse sind.\n\nEs ist hilfreich, im Sinne des vierten Prinzips (Konsistenz) sich nach einer\nbekannten, vielleicht sogar verbreiteten Nomenklatur bzw. Vorgehensweise zu richten.\nFür Bayes-Analysen gibt es dazu Richtlinien und Checklisten; \ndie folgenden Hinweise orientieren sich an @kruschke_bayesian_2021, genannt *BARG* (Bayesian Analysis Reporting Guidelines);\nder Volltext ist [hier](https://www.nature.com/articles/s41562-021-01177-7) zugänglich.\nAuch die APA (American Psychological Assocation) hat eine [Checkliste herausgegeben](https://data-se.netlify.app/2022/01/27/warum-bayes/),\nwie Bayes-Statistik berichtet werden sollte.\n\n\nDie wichtigsten Ergebnisse der BARG sind [in dieser Tabelle ausgelegt](https://www.nature.com/articles/s41562-021-01177-7/tables/1).\nIm folgenden wird eine Auswahl der BARG vorgestellt.\nDas Ziel ist nicht eine umfassende Darstellung mit einer hohen Tiefe der Exposition.\nVielmehr soll - angepasst an den Kenntnissstand von Bachelor-Studentis - ein\nangemessener Überblick ausgewählt werden.\nAmbitionierte Studentis sind aufgefordert, breite und tiefer als in der folgenden Ausführtung erläutert,\nzu berichten.\nDie folgende Ausführung orientiert sich an der Standardgliederung wissenschaftlicher Berichte.\n\nLesis seien verwiesen auf das Buch von  @jhangiani_research_2019,\ndie einen hervorragenden Überblick über die Materie vermitteln.\n\n\n\n\n## Allgemeine Richtlinien zum Berichten von Statistik\n\n\nDie APA hat eine [Checkliste bzw. Richtlinie herausgegeben zum Berichten von Statistik](https://www.apa.org/pubs/authors/jars.pdf) [vgl. @cooper_reporting_2020].\nDie lesenswerten Schwesterbüch von @peters_planen_2019 bzw. @peters_abschlussarbeiten_2015 geben nicht nur Formulierungshilfen,\nsondern erläutern, wie man eine sinnvolle Gliederung erstellt und welche Inhalte in welchem Abschnitt gehören.\n\nGrundlegende Prinzipien des Berichtens von Statistiken sind:\n\n1. Begründet: Eine Erläuterung, warum ein Vorgehen gewählt wurde, wird gegeben.\n2. Nachvollziehbar: Lesis können anhand des Berichts (potenziell) nachvollziehen, wie die Autoren zu einem Ergebnis gelangt sind.\n3. Von einfach zu komplex: Es ist verbreitet, zunächst grundlegende Ergebnisse, dann komplexere Modellanalysen zu präsentieren.\n4. Deskriptiv: Ergebnisse werden berichtet, aber nicht bewertet (das kommt erst im Diskussionsteil).\n5. Lauter: Alle relevanten Ergebnisse werden offengelegt.\n\n\n:::{.callout-note}\nIn @sec-schreiben finden Sie Vorschläge zum Gliedern Ihres Berichts. $\\square$\n:::\n\n\n\n\n\n\n\n\n## Statistiken berichten im Ergebnisteil {#sec-statistik-ergebnisteil}\n\n:::{.callout-note}\nEinen Gliederungsvorschlag für Ihren Ergebnisteil finden Sie in @sec-ergebnisteil. Dort finden Sie z.B. auch Hinweise zur Gestaltung von Abbildungen, s. @sec-abbildungen. $\\square$\n:::\n\n\n### Datenaufbereitung\n\nFalls Sie die Daten aufbereiten mussten in einem Maße, dass übliche, notwendige Operationen übersteigt, sollten Sie kurz berichten, was Sie getan haben. Wenn Sie lediglich die Daten mit Operationen wie Scores berechnet oder Variablen zentriert aufbereitet haben, müssen Sie nichts weiter berichten. \nSie sollten dabei keine Syntax (z.B. R-Code) aufführen; dafür ist ggf. Platz im Anhang.\n\n### Deskriptive Statistik\n\n#### Was soll ich schreiben?\n\n\nBevor Sie die Ergebnisse Ihrer Modellierung zeigen,\nbietet sich etwas \"Aufwärmen\" an,\nvor dem Fußballspiel wärmt man sich ja auch erstmal auf.\nDazu bieten sich die *deskriptiven Statistiken* zu Ihren Daten an.\n\nHäufig wird man ein Maß der zentralen Tendenz (Mittelwert oder Median) sowie \nein dazu passendes Streuungsmaß berichten (z.B. SD) berichten.\nEvtl. kann man ein Maß zur Präzision des Mittelwerts angeben (SE).\nBei schiefen Verteilungen greift man meist auf robuste Kennwerte zurück;\nbei normalverteilten Verteilungen ist Mittelwert und SD die Statistik der Wahl.\nDie Stichprobengröße sollte klar sein; \nliegen fehlende Werte vor, so sollte pro Kennzahl jeweils die effektive Stichprobengröße berichtet sein.\nAnsonsten reicht es, die Stichprobengröße an einer Stelle (im Text) anzuführen.\n\n\nGängige statistische Symbole sollen nicht definiert werden, z.B. *M*, *SD*, *F*, *t*, *df*, *N*, *n*, *OR*.  Andere statistischen Abkürzungen, die weniger gebräuchlich sind,\nsollten definiert bzw. auf die Definition verwiesen werden, z.B. *pd*, *ROPE*.\n\n\n*Formulierungsvorschlag*\n\n>   Der mittlere Achtsamkeits-Wert lag in der Stichprobe bei *M* = 12.23 (*SD* = 1.23).\n\n>   Die Reaktionszeit in der Experimentalbedingung war höher als in der Kontrollbedingung (Experimentalbedingung: *M* = 2.7, *SD* = 0.3; Kontrollbedingung: *M* = 0.1, *SD* = 0.4).\n\n>   Es fand sich eine starke Korrelation zwischen Achtsamkeit und Lebenszufriedenheit, r(134) = .42, 95% CI [.32, .52].\n\nHat man eine größere Zahl an Statistiken,\nso bietet es sich an, die Ergebnisse nicht im Fließtext, sondern in einer Tabelle zu berichten.\nBerichtet man Ergebnisse in einer Tabelle, so doppelt man sie nicht im Text.\n\n\nEine nützliche Ergänzung ist es,\nzusätzlich zu den univariaten Statistiken noch Zusammenhangskoeffizienten (Korrelationen) zu berichten.\n\n#### Tabellen mit R\n\nIm folgenden sind Möglichkeiten aufgezeigt, wie Sie Tabellen mit R für Ihren Bericht erstellen können.\nBitte behalten Sie im Blick, dass in einem deutschsprachigen Bericht die Variablen- und Kennzahlennamen in deutscher Sprache erscheinen sollten.\nAuf \"technisch\" anmutenden Abkürzungen (z.B. `mpg_sd`) sollten man verzichten zugunsten \"sprechenderer\" Formulierengen (z.B. *SD Spritverbrauch*, oder *SD MPG*, wenn \"MPG\" in der Fußnote der Tabelle definiert ist).\nTabellen sollten für sich selber verständlich sein, ohne Bezug zum Text.\n\nMit gängigen R-Methoden kann man sich deskriptive Statistiken ausgeben lassen, s. @tbl-desk1.\n\n\n\n\n::: {#tbl-desk1 .cell tbl-cap='Einfache Tabelle mit deskriptiven Statistiken'}\n\n```{.r .cell-code}\nmtcars %>% \n  summarise(mpg_avg = mean(mpg),\n            mpg_sd = sd(mpg),\n            cor_mpg_hp = cor(mpg, hp)) %>% \n  rename(`MW Spritverbrauch` = mpg_avg,\n         `SD Spritverbrauch`= mpg_sd,\n         `Korrelation Spritverbrauch mit PS-Zahl` = cor_mpg_hp)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"MW Spritverbrauch\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SD Spritverbrauch\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Korrelation Spritverbrauch mit PS-Zahl\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"20.09062\",\"2\":\"6.026948\",\"3\":\"-0.7761684\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n\n\n\nAlternativ zu selbsterstellten Tabellen kann \"Statistik-Fast-Food\" konsumieren und lässt sich einen Haufen Zahlen auf einmal ausgeben.\n R-Pakete wie `r_statix`, `skimr` oder `easystats` helfen dabei, s. als Beispiel @tbl-desk2.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(easystats)\n\ndescribe_distribution(mtcars) %>% \n  select(-n, -n_Missing) %>% \n  rename(MW = Mean, Schiefe = Skewness)\n```\n:::\n\n::: {#tbl-desk2 .cell tbl-cap='Einfache Tabelle mit describe_distribution aus easystats'}\n::: {.cell-output-display}\n\n\n|Variable |     MW |     SD |    IQR |           Range | Schiefe | Kurtosis |\n|:--------|:------:|:------:|:------:|:---------------:|:-------:|:--------:|\n|mpg      |  20.09 |   6.03 |   7.53 |  (10.40, 33.90) |    0.67 |    -0.02 |\n|cyl      |   6.19 |   1.79 |   4.00 |    (4.00, 8.00) |   -0.19 |    -1.76 |\n|disp     | 230.72 | 123.94 | 221.53 | (71.10, 472.00) |    0.42 |    -1.07 |\n|hp       | 146.69 |  68.56 |  84.50 | (52.00, 335.00) |    0.80 |     0.28 |\n|drat     |   3.60 |   0.53 |   0.84 |    (2.76, 4.93) |    0.29 |    -0.45 |\n|wt       |   3.22 |   0.98 |   1.19 |    (1.51, 5.42) |    0.47 |     0.42 |\n|qsec     |  17.85 |   1.79 |   2.02 |  (14.50, 22.90) |    0.41 |     0.86 |\n|vs       |   0.44 |   0.50 |   1.00 |    (0.00, 1.00) |    0.26 |    -2.06 |\n|am       |   0.41 |   0.50 |   1.00 |    (0.00, 1.00) |    0.40 |    -1.97 |\n|gear     |   3.69 |   0.74 |   1.00 |    (3.00, 5.00) |    0.58 |    -0.90 |\n|carb     |   2.81 |   1.62 |   2.00 |    (1.00, 8.00) |    1.16 |     2.02 |\n\n\n:::\n:::\n\n\n\n\n\nTabellen mit `flextable()`, [`gtsummary`](https://education.rstudio.com/blog/2020/07/gtsummary/) oder `gt()` kann man sich eine schicke Tabelle (im HTML-Format) ausgeben lassen,\ndie man dann per Copy-Paste in Word, d.h. den eigene Forschungsbericht, übernehmen kann.\ns. @tbl-gt1.\n\n\n\n\n\n::: {#tbl-gt1 .cell tbl-cap='Deskriptive Statistiken mit gt'}\n\n```{.r .cell-code}\nlibrary(gt)  # gt wie \"grammer of tables\"\n\nmeine_tab <- \n  describe_distribution(mtcars) %>% \n  gt() %>%  # erzeugt schicke Tabelle\n  fmt_number(where(is.numeric), decimals = 2) # Anzahl der Dezimalstellen\n\nmeine_tab\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vinyulsuyk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vinyulsuyk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vinyulsuyk thead, #vinyulsuyk tbody, #vinyulsuyk tfoot, #vinyulsuyk tr, #vinyulsuyk td, #vinyulsuyk th {\n  border-style: none;\n}\n\n#vinyulsuyk p {\n  margin: 0;\n  padding: 0;\n}\n\n#vinyulsuyk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vinyulsuyk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vinyulsuyk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vinyulsuyk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vinyulsuyk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vinyulsuyk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vinyulsuyk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vinyulsuyk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vinyulsuyk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vinyulsuyk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vinyulsuyk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vinyulsuyk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vinyulsuyk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vinyulsuyk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vinyulsuyk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vinyulsuyk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vinyulsuyk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vinyulsuyk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vinyulsuyk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vinyulsuyk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vinyulsuyk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vinyulsuyk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vinyulsuyk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vinyulsuyk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vinyulsuyk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vinyulsuyk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vinyulsuyk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vinyulsuyk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vinyulsuyk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vinyulsuyk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vinyulsuyk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vinyulsuyk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vinyulsuyk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vinyulsuyk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vinyulsuyk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vinyulsuyk .gt_left {\n  text-align: left;\n}\n\n#vinyulsuyk .gt_center {\n  text-align: center;\n}\n\n#vinyulsuyk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vinyulsuyk .gt_font_normal {\n  font-weight: normal;\n}\n\n#vinyulsuyk .gt_font_bold {\n  font-weight: bold;\n}\n\n#vinyulsuyk .gt_font_italic {\n  font-style: italic;\n}\n\n#vinyulsuyk .gt_super {\n  font-size: 65%;\n}\n\n#vinyulsuyk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vinyulsuyk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vinyulsuyk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vinyulsuyk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vinyulsuyk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vinyulsuyk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vinyulsuyk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vinyulsuyk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vinyulsuyk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Variable\">Variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Mean\">Mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SD\">SD</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"IQR\">IQR</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Min\">Min</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Max\">Max</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Skewness\">Skewness</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Kurtosis\">Kurtosis</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_Missing\">n_Missing</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">mpg</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">20.09</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">6.03</td>\n<td headers=\"IQR\" class=\"gt_row gt_right\">7.53</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">10.40</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">33.90</td>\n<td headers=\"Skewness\" class=\"gt_row gt_right\">0.67</td>\n<td headers=\"Kurtosis\" class=\"gt_row gt_right\">−0.02</td>\n<td headers=\"n\" class=\"gt_row gt_right\">32.00</td>\n<td headers=\"n_Missing\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">cyl</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">6.19</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">1.79</td>\n<td headers=\"IQR\" class=\"gt_row gt_right\">4.00</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">4.00</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">8.00</td>\n<td headers=\"Skewness\" class=\"gt_row gt_right\">−0.19</td>\n<td headers=\"Kurtosis\" class=\"gt_row gt_right\">−1.76</td>\n<td headers=\"n\" class=\"gt_row gt_right\">32.00</td>\n<td headers=\"n_Missing\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">disp</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">230.72</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">123.94</td>\n<td headers=\"IQR\" class=\"gt_row gt_right\">221.53</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">71.10</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">472.00</td>\n<td headers=\"Skewness\" class=\"gt_row gt_right\">0.42</td>\n<td headers=\"Kurtosis\" class=\"gt_row gt_right\">−1.07</td>\n<td headers=\"n\" class=\"gt_row gt_right\">32.00</td>\n<td headers=\"n_Missing\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">hp</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">146.69</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">68.56</td>\n<td headers=\"IQR\" class=\"gt_row gt_right\">84.50</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">52.00</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">335.00</td>\n<td headers=\"Skewness\" class=\"gt_row gt_right\">0.80</td>\n<td headers=\"Kurtosis\" class=\"gt_row gt_right\">0.28</td>\n<td headers=\"n\" class=\"gt_row gt_right\">32.00</td>\n<td headers=\"n_Missing\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">drat</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">3.60</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">0.53</td>\n<td headers=\"IQR\" class=\"gt_row gt_right\">0.84</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">2.76</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">4.93</td>\n<td headers=\"Skewness\" class=\"gt_row gt_right\">0.29</td>\n<td headers=\"Kurtosis\" class=\"gt_row gt_right\">−0.45</td>\n<td headers=\"n\" class=\"gt_row gt_right\">32.00</td>\n<td headers=\"n_Missing\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">wt</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">3.22</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">0.98</td>\n<td headers=\"IQR\" class=\"gt_row gt_right\">1.19</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">1.51</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">5.42</td>\n<td headers=\"Skewness\" class=\"gt_row gt_right\">0.47</td>\n<td headers=\"Kurtosis\" class=\"gt_row gt_right\">0.42</td>\n<td headers=\"n\" class=\"gt_row gt_right\">32.00</td>\n<td headers=\"n_Missing\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">qsec</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">17.85</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">1.79</td>\n<td headers=\"IQR\" class=\"gt_row gt_right\">2.02</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">14.50</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">22.90</td>\n<td headers=\"Skewness\" class=\"gt_row gt_right\">0.41</td>\n<td headers=\"Kurtosis\" class=\"gt_row gt_right\">0.86</td>\n<td headers=\"n\" class=\"gt_row gt_right\">32.00</td>\n<td headers=\"n_Missing\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">vs</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">0.44</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">0.50</td>\n<td headers=\"IQR\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"Skewness\" class=\"gt_row gt_right\">0.26</td>\n<td headers=\"Kurtosis\" class=\"gt_row gt_right\">−2.06</td>\n<td headers=\"n\" class=\"gt_row gt_right\">32.00</td>\n<td headers=\"n_Missing\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">am</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">0.41</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">0.50</td>\n<td headers=\"IQR\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"Skewness\" class=\"gt_row gt_right\">0.40</td>\n<td headers=\"Kurtosis\" class=\"gt_row gt_right\">−1.97</td>\n<td headers=\"n\" class=\"gt_row gt_right\">32.00</td>\n<td headers=\"n_Missing\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">gear</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">3.69</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">0.74</td>\n<td headers=\"IQR\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">3.00</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">5.00</td>\n<td headers=\"Skewness\" class=\"gt_row gt_right\">0.58</td>\n<td headers=\"Kurtosis\" class=\"gt_row gt_right\">−0.90</td>\n<td headers=\"n\" class=\"gt_row gt_right\">32.00</td>\n<td headers=\"n_Missing\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">carb</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">2.81</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">1.62</td>\n<td headers=\"IQR\" class=\"gt_row gt_right\">2.00</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">8.00</td>\n<td headers=\"Skewness\" class=\"gt_row gt_right\">1.16</td>\n<td headers=\"Kurtosis\" class=\"gt_row gt_right\">2.02</td>\n<td headers=\"n\" class=\"gt_row gt_right\">32.00</td>\n<td headers=\"n_Missing\" class=\"gt_row gt_right\">0.00</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nAus APA-Sicht würde vermutlich MW und SD genüge tun (sofern man von normalverteilten Variablen) ausgeht.\nAllerdings schadet es auch nicht, zusätzliche Kennwerte anzugeben.\nVerzichten sollte man aber vermutlih - in diesem Fall - auf die Spalte `n_Missing`,\nda die Spalte keine Information birgt.\n\nSo sieht eine Tabelle mit `gtsummary` aus, s. @tbl-gtsum1.\nHier wird die Häufigkeitsanalyse gezeigt.\n\n\n\n\n::: {#tbl-gtsum1 .cell tbl-cap='Deskriptive Statistiken mit gtsummary'}\n\n```{.r .cell-code}\nlibrary(gtsummary)\nmtcars %>% \n  select(mpg, cyl) %>% \n  tbl_summary()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"nxjjddpdxt\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nxjjddpdxt table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nxjjddpdxt thead, #nxjjddpdxt tbody, #nxjjddpdxt tfoot, #nxjjddpdxt tr, #nxjjddpdxt td, #nxjjddpdxt th {\n  border-style: none;\n}\n\n#nxjjddpdxt p {\n  margin: 0;\n  padding: 0;\n}\n\n#nxjjddpdxt .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nxjjddpdxt .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nxjjddpdxt .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nxjjddpdxt .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nxjjddpdxt .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nxjjddpdxt .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nxjjddpdxt .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nxjjddpdxt .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nxjjddpdxt .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nxjjddpdxt .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nxjjddpdxt .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nxjjddpdxt .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nxjjddpdxt .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nxjjddpdxt .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nxjjddpdxt .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nxjjddpdxt .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nxjjddpdxt .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nxjjddpdxt .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nxjjddpdxt .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nxjjddpdxt .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nxjjddpdxt .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nxjjddpdxt .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nxjjddpdxt .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nxjjddpdxt .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nxjjddpdxt .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nxjjddpdxt .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nxjjddpdxt .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nxjjddpdxt .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nxjjddpdxt .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nxjjddpdxt .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nxjjddpdxt .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nxjjddpdxt .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nxjjddpdxt .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nxjjddpdxt .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nxjjddpdxt .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nxjjddpdxt .gt_left {\n  text-align: left;\n}\n\n#nxjjddpdxt .gt_center {\n  text-align: center;\n}\n\n#nxjjddpdxt .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nxjjddpdxt .gt_font_normal {\n  font-weight: normal;\n}\n\n#nxjjddpdxt .gt_font_bold {\n  font-weight: bold;\n}\n\n#nxjjddpdxt .gt_font_italic {\n  font-style: italic;\n}\n\n#nxjjddpdxt .gt_super {\n  font-size: 65%;\n}\n\n#nxjjddpdxt .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nxjjddpdxt .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nxjjddpdxt .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nxjjddpdxt .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nxjjddpdxt .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nxjjddpdxt .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nxjjddpdxt .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#nxjjddpdxt .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#nxjjddpdxt div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"PHN0cm9uZz5DaGFyYWN0ZXJpc3RpYzwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_0\"><span data-qmd-base64=\"PHN0cm9uZz5OID0gMzI8L3N0cm9uZz4=\"><span class='gt_from_md'><strong>N = 32</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">mpg</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">19.2 (15.4, 22.8)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">cyl</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    4</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">11 (34%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    6</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">7 (22%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    8</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">14 (44%)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVkaWFuIChRMSwgUTMpOyBuICglKQ==\"><span class='gt_from_md'>Median (Q1, Q3); n (%)</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n[Hier](https://data-se.netlify.app/2022/05/02/kontigenztabellen-in-r/#exportieren) findet sich noch mehr zum Thema Exportieren von Tabellen aus R nach Word.\n\nEine *tidy* Korrelationstabelle kann man sich z.B. (mit `easystats`, aber es gibt mehrere R-Pakete für diesen Zweck) so ausgeben lassen:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeine_cor_tab <-\n  mtcars %>% \n  select(mpg, hp, disp) %>% \n  correlation()\n\nmeine_cor_tab %>% print_md()\n```\n\n::: {.cell-output-display}\n\n\nTable: Correlation Matrix (pearson-method)\n\n|Parameter1 | Parameter2 |     r |         95% CI | t(30) |         p |\n|:----------|:----------:|:-----:|:--------------:|:-----:|:---------:|\n|mpg        |         hp | -0.78 | (-0.89, -0.59) | -6.74 | < .001*** |\n|mpg        |       disp | -0.85 | (-0.92, -0.71) | -8.75 | < .001*** |\n|hp         |       disp |  0.79 |   (0.61, 0.89) |  7.08 | < .001*** |\np-value adjustment method: Holm (1979)\nObservations: 32\n\n\n:::\n:::\n\n\n\n\n\n:::{.callout-note}\nMit `print_md` erreicht man, dass die Tabelle in schönerem Markdown-Format gedruckt wird.\nDa Markdown sich problemlos in HTML- oder Word-Format konvertieren lässt, kann man auf diese Art schöner formatierte Tabellen erhalten (als mit dem Standard von `describe_distribution` and friends). `gt` ist allerdings schon von Natur aus schön.$\\square$\n:::\n\nMöchte man eine *quadratische* Korrelationstabelle (was der üblicheren Berichtsform entspricht) kann man das so bekommen:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(meine_cor_tab) %>% \n  gt() %>%  # machen wir gleich eine schicke HTML-Tabelle\n  fmt_number(where(is.numeric), decimals = 2)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hmnzceukih\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hmnzceukih table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hmnzceukih thead, #hmnzceukih tbody, #hmnzceukih tfoot, #hmnzceukih tr, #hmnzceukih td, #hmnzceukih th {\n  border-style: none;\n}\n\n#hmnzceukih p {\n  margin: 0;\n  padding: 0;\n}\n\n#hmnzceukih .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hmnzceukih .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hmnzceukih .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hmnzceukih .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hmnzceukih .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hmnzceukih .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hmnzceukih .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hmnzceukih .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hmnzceukih .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hmnzceukih .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hmnzceukih .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hmnzceukih .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hmnzceukih .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hmnzceukih .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hmnzceukih .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hmnzceukih .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hmnzceukih .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hmnzceukih .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hmnzceukih .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hmnzceukih .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hmnzceukih .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hmnzceukih .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hmnzceukih .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hmnzceukih .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hmnzceukih .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hmnzceukih .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hmnzceukih .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hmnzceukih .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hmnzceukih .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hmnzceukih .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hmnzceukih .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hmnzceukih .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hmnzceukih .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hmnzceukih .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hmnzceukih .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hmnzceukih .gt_left {\n  text-align: left;\n}\n\n#hmnzceukih .gt_center {\n  text-align: center;\n}\n\n#hmnzceukih .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hmnzceukih .gt_font_normal {\n  font-weight: normal;\n}\n\n#hmnzceukih .gt_font_bold {\n  font-weight: bold;\n}\n\n#hmnzceukih .gt_font_italic {\n  font-style: italic;\n}\n\n#hmnzceukih .gt_super {\n  font-size: 65%;\n}\n\n#hmnzceukih .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hmnzceukih .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hmnzceukih .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hmnzceukih .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hmnzceukih .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hmnzceukih .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hmnzceukih .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hmnzceukih .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hmnzceukih div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Parameter\">Parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"disp\">disp</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"hp\">hp</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\">mpg</td>\n<td headers=\"disp\" class=\"gt_row gt_right\">−0.85</td>\n<td headers=\"hp\" class=\"gt_row gt_right\">−0.78</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\">hp</td>\n<td headers=\"disp\" class=\"gt_row gt_right\">0.79</td>\n<td headers=\"hp\" class=\"gt_row gt_right\">NA</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nVergessen Sie nicht, das Tabellen (genau wie Abbildungen) im Text zu referenzieren sind.\n\n\n:::{.callout-note}\nWeitere Hinweise zur Gestaltung von Tabellen finden Sie in @sec-formatierung-tabellen. $\\square$\n:::\n\n\n\n### Inferenzstatistik\n\nEs empfiehlt sich, die Modellgleichung inkl. Prior-Spezifiaktion aufzuführen.\n\n#### Posteriori-Verteilung\n\nFür jede Hypothese müssen Sie die zentralen Ergebnisse berichten.\nDie Hypothesen beziehen sich auf Populationen, \nalso benötigen wir Inferenzstatistik.\nIn der frequentistischen Statistik finden hier Statistiken wie der *p*-Wert und\ndas (frequentistische) Konfidenzintervall Verwendung.\nIn einer Bayes-Analyse ist die Posteriori-Verteilung der Dreh- und Angelpunkt der Ergebnisse.\n\nZur Erinnerung: Die Post-Verteilung gibt an, wie wahrscheinlich ein bestimmter Parameterwert jetzt ist,\nnachdem die Daten bekannt sind.\n\n\nEin statistisches Modell wird zumeist mit einem Regressionsmodell umgesetzt.\nEin Regressionsmodell kann man in R mit `lm()` (frequentistisch) oder z.B. `stan_glm()` (Bayes) berechnen.\nDie Syntax ist sehr ähnlich.\n\n\n\n#### Umsetzung in R\n\n:::{.callout-note}\nDetailliertere Hinweise zur Modellierung finden Sie @sec-modellieren. $\\square$\n:::\n\nSie können eine Posteriori-Verteilung z.B. für ihr Modell berechnen:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rstanarm)\n\nm1 <- stan_glm(mpg ~ am, data = mtcars, seed = 42)\n```\n:::\n\n\n\n\nHier sind die Ergebnisse; noch nicht ganz poliert für einen APA-Bericht, s. @tbl-m1-params.\n\n\n\n\n::: {#tbl-m1-params .cell tbl-cap='Parameter für das Modell m1'}\n\n```{.r .cell-code}\nparameters(m1, prob = .95) %>% \n  print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Median |         95% CI |     pd |  Rhat |     ESS |                   Prior |\n|:-----------|:------:|:--------------:|:------:|:-----:|:-------:|:-----------------------:|\n|(Intercept) |  17.14 | (14.85, 19.51) |   100% | 0.999 | 3739.00 | Normal (20.09 +- 15.07) |\n|am          |   7.21 |  (3.72, 10.70) | 99.95% | 0.999 | 3755.00 |  Normal (0.00 +- 30.20) |\n\n\n:::\n:::\n\n\n\n\n\nWir bekommen ein 95%-Perzentilintervall (PI, kein HDI, ist aber auch ok, allerdings ist das HDI einen Tick besser).\nEs erlaubt uns zu sagen, dass der Unterschied im Spritverbrauch zwischen 3.6 und 11 Meilen (pro Gallone Sprit) liegt,\nlaut dem Modell.\nDer Schalter `prob` erlaubt, andere CI-Breiten, z.B. 97% zu wählen.\n\n\nFormulierungsvorschlag:\n\n>    Der statistische Effekt der Schaltung auf den Spritverbrauch wurde vom Modell auf 7.21 geschätzt, 95%-PI [3.72, 10.70]. Da die Null nicht im Intervall liegt, kann die Nullhypothese ausgeschlossen werden.\n\nEin HDI bekommen Sie, wenn Sie bei `ci_method` den Wert `\"hdi` wählen;\noder wenn Sie gleich den Befehl `hdi(m1)` ausführen, s. @tbl-m1-params2.\n\n\n\n\n::: {#tbl-m1-params2 .cell tbl-cap='Parameter für das Modell m1. Das Intervall ist ein HDI.'}\n\n```{.r .cell-code}\nparameters(m1, prob = .95, ci_method = \"hdi\") %>% print_md()  # oder: hdi(m1)\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Median |         95% CI |     pd |  Rhat |     ESS |                   Prior |\n|:-----------|:------:|:--------------:|:------:|:-----:|:-------:|:-----------------------:|\n|(Intercept) |  17.14 | (14.95, 19.59) |   100% | 0.999 | 3739.00 | Normal (20.09 +- 15.07) |\n|am          |   7.21 |  (3.67, 10.62) | 99.95% | 0.999 | 3755.00 |  Normal (0.00 +- 30.20) |\n\n\n:::\n:::\n\n\n\n\nDie Tabelle können Sie natürlich auch gleich wieder aufhübschen, für Ihren Bericht, s. @tbl-m1-params3.\n\n\n\n\n::: {#tbl-m1-params3 .cell tbl-cap='Parameter für das Modell m1. Das Intervall ist ein HDI.'}\n\n```{.r .cell-code}\nhdi(m1) %>% \n  select(Parameter, CI_low, CI_high) %>% \n  gt() %>% \n  fmt_number(where(is.numeric), decimals = 2)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"mpzkeybnmo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mpzkeybnmo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mpzkeybnmo thead, #mpzkeybnmo tbody, #mpzkeybnmo tfoot, #mpzkeybnmo tr, #mpzkeybnmo td, #mpzkeybnmo th {\n  border-style: none;\n}\n\n#mpzkeybnmo p {\n  margin: 0;\n  padding: 0;\n}\n\n#mpzkeybnmo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mpzkeybnmo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mpzkeybnmo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mpzkeybnmo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mpzkeybnmo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mpzkeybnmo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mpzkeybnmo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mpzkeybnmo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mpzkeybnmo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mpzkeybnmo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mpzkeybnmo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mpzkeybnmo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mpzkeybnmo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mpzkeybnmo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mpzkeybnmo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mpzkeybnmo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mpzkeybnmo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mpzkeybnmo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mpzkeybnmo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mpzkeybnmo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mpzkeybnmo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mpzkeybnmo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mpzkeybnmo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mpzkeybnmo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mpzkeybnmo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mpzkeybnmo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mpzkeybnmo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mpzkeybnmo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mpzkeybnmo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mpzkeybnmo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mpzkeybnmo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mpzkeybnmo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mpzkeybnmo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mpzkeybnmo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mpzkeybnmo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mpzkeybnmo .gt_left {\n  text-align: left;\n}\n\n#mpzkeybnmo .gt_center {\n  text-align: center;\n}\n\n#mpzkeybnmo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mpzkeybnmo .gt_font_normal {\n  font-weight: normal;\n}\n\n#mpzkeybnmo .gt_font_bold {\n  font-weight: bold;\n}\n\n#mpzkeybnmo .gt_font_italic {\n  font-style: italic;\n}\n\n#mpzkeybnmo .gt_super {\n  font-size: 65%;\n}\n\n#mpzkeybnmo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mpzkeybnmo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mpzkeybnmo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mpzkeybnmo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mpzkeybnmo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mpzkeybnmo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mpzkeybnmo .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#mpzkeybnmo .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#mpzkeybnmo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Parameter\">Parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CI_low\">CI_low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CI_high\">CI_high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"CI_low\" class=\"gt_row gt_right\">14.95</td>\n<td headers=\"CI_high\" class=\"gt_row gt_right\">19.59</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\">am</td>\n<td headers=\"CI_low\" class=\"gt_row gt_right\">3.67</td>\n<td headers=\"CI_high\" class=\"gt_row gt_right\">10.62</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\nEin ähnliches Ergebnis erzielt man mit dem Paket `gtsummary`, s. @tbl-m1-params4.\n\n\n\n\n\n::: {#tbl-m1-params4 .cell tbl-cap='Parameter für das Modell m1.'}\n\n```{.r .cell-code}\ntbl_regression(m1)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vjrjiaolra\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vjrjiaolra table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vjrjiaolra thead, #vjrjiaolra tbody, #vjrjiaolra tfoot, #vjrjiaolra tr, #vjrjiaolra td, #vjrjiaolra th {\n  border-style: none;\n}\n\n#vjrjiaolra p {\n  margin: 0;\n  padding: 0;\n}\n\n#vjrjiaolra .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vjrjiaolra .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vjrjiaolra .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vjrjiaolra .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vjrjiaolra .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vjrjiaolra .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vjrjiaolra .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vjrjiaolra .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vjrjiaolra .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vjrjiaolra .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vjrjiaolra .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vjrjiaolra .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vjrjiaolra .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vjrjiaolra .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vjrjiaolra .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vjrjiaolra .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vjrjiaolra .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vjrjiaolra .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vjrjiaolra .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vjrjiaolra .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vjrjiaolra .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vjrjiaolra .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vjrjiaolra .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vjrjiaolra .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vjrjiaolra .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vjrjiaolra .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vjrjiaolra .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vjrjiaolra .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vjrjiaolra .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vjrjiaolra .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vjrjiaolra .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vjrjiaolra .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vjrjiaolra .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vjrjiaolra .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vjrjiaolra .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vjrjiaolra .gt_left {\n  text-align: left;\n}\n\n#vjrjiaolra .gt_center {\n  text-align: center;\n}\n\n#vjrjiaolra .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vjrjiaolra .gt_font_normal {\n  font-weight: normal;\n}\n\n#vjrjiaolra .gt_font_bold {\n  font-weight: bold;\n}\n\n#vjrjiaolra .gt_font_italic {\n  font-style: italic;\n}\n\n#vjrjiaolra .gt_super {\n  font-size: 65%;\n}\n\n#vjrjiaolra .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vjrjiaolra .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vjrjiaolra .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vjrjiaolra .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vjrjiaolra .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vjrjiaolra .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vjrjiaolra .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vjrjiaolra .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vjrjiaolra div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"PHN0cm9uZz5DaGFyYWN0ZXJpc3RpYzwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"PHN0cm9uZz5CZXRhPC9zdHJvbmc+\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"PHN0cm9uZz45NSUgQ0k8L3N0cm9uZz4=\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">am</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">7.2</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">3.7, 11</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"3\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uOiBDSSA9IENyZWRpYmxlIEludGVydmFs\"><span class='gt_from_md'>Abbreviation: CI = Credible Interval</span></span></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\nDen Punktschätzer (`Median`) zum Unterschied für die Gruppen (Automatik vs. Schaltgetriebe) hat uns die Funktion `parameters()` auch geliefert. Der Unterschied zwischen den beiden Gruppen liegt laut Modell bei ca. 7.2 Meilen.\n\n\n\n\nEs bietet sich an, die Parameter-Schätzbereiche zu visualisieren.\nDas kann man z.B. so machen:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparameters(m1) %>% plot(show_intercept = TRUE)\n```\n\n::: {.cell-output-display}\n![](100-Statistiken-berichten_files/figure-html/unnamed-chunk-14-1.png){width=100%}\n:::\n:::\n\n\n\n\nDer Schalter `show_intercept` regelt, ob der Schätzwert für den Achsenabschnitt gezeigt werden soll oder nicht.^[Hat man *nur* einen Intercept, so muss man den Schalter auf `TRUE` setzen, will man nicht mit einer Fehlermeldung abgestraft werden.]\n\n\n\nMöchte man verschiedenen Regressiongsgewichte vergleichen,\nbietet es an, diese vorab zu standardisieren mit der z-Transformation.\n\n\nMehr zur Analyse mit `rstanarm` findet sich z.B. [hier](http://mc-stan.org/rstanarm/articles/rstanarm.html) oder bei @gelman_regression_2021.\n\n\nÜbrigens kann man ein `hdi()` auch plotten,\nwenn man möchte:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(hdi(m1))\n```\n:::\n\n\n\n\n\nSieht auch ganz schick aus; im Hintergrund wird `{easystats}` zum Plotten verwendet.\nPraktischerweise ist es ein ggplot-Diagramm, \nman kann also mit bekannten (ggplot-)Methoden nachpolieren, z.B s. @fig-m1-hdi.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(hdi(m1)) +\n  labs(title =\"Hier steht mein Titel\",\n       y = \"\",\n       y = \"\",\n       x = \"Parameterwert\") +\n  theme_minimal() +\n  theme(axis.text.y = element_blank())  # keine Achsenlabels auf Y (\"am\" weg)\n```\n\n::: {.cell-output-display}\n![Die Postverteilung als Berg visualisiert, nicht als Seil.](100-Statistiken-berichten_files/figure-html/fig-m1-hdi-1.png){#fig-m1-hdi width=672}\n:::\n:::\n\n\n\n\n\n\n#### ROPE\n\nTesten Sie eine Hypothese, die einen \"praktischen Nullwert\" ausschließen möchte, so bietet sich das ROPE-Verfahren an.\n\nMit ROPE testet man demnach keine \"Exaktnullhypothese\", sondern eine \"Praktischnullhypothese\",\nnämlich dass ein Effekt so klein ist, dass er praktisch keine Bedeutung hat.\n\nDiesem Konzept liegt die Überlegung zugrunde,\ndass es in der freien Wildbahn kaum oder keine Effekte gibt,\ndie *exakt* Null sind, also \"0,0000000000000000000000000 ...\" und so weiter bis alle Unendlichkeit.\n\nSinnvoller ist es daher zu prüfen, ob ein Effekt *vernachlässigbar klein* ist für\npraktische Belange.\n\nWie klein ein Effekt sein muss, um \"klein genug\" für \"vernachlässigbar klein\" zu sein,\nist erstmal keine statistische Frage.\n\nSchauen Sie: Wie groß muss der Nutzen des Besuchens einer Vorlesung sein,\ndamit Sie sie besuchen? Die Antwort der Frage hängt von mehreren Faktoren ab,\nund sie ist subjektiv in dem Sinne, dass die Antwort von persönlichen Präferenzen abhängt,\ndie letztlich nicht objektiv zu begründen sind.\n\n\nSo kann man in R ein ROPE berechnen (lassen):‚\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(easystats)\n\nrope(m1)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Parameter\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"CI\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"ROPE_low\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"ROPE_high\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"ROPE_Percentage\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Effects\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Component\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"(Intercept)\",\"2\":\"0.95\",\"3\":\"-0.6026948\",\"4\":\"0.6026948\",\"5\":\"0\",\"6\":\"fixed\",\"7\":\"conditional\",\"_rn_\":\"1\"},{\"1\":\"am\",\"2\":\"0.95\",\"3\":\"-0.6026948\",\"4\":\"0.6026948\",\"5\":\"0\",\"6\":\"fixed\",\"7\":\"conditional\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n\n\nDas Ergebnis sagt uns, dass 0% des 95%-HDI innerhalb des ROPE-Bereichs liegen.\nDie Nullhypothese ist also für praktische Zwecke auszuschließen.\n\n*Formulierungsvorschlag*\n>   Die Nullhypothese $H^1_0$ ist auszuschließen laut Modell m1, 0% ROPE. Der Effekt ist demnach in diesem Sinne signifikant.\n\n\n\n\nDas kann man sich auch plotten lassen:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(rope(m1))\n```\n\n::: {.cell-output-display}\n![](100-Statistiken-berichten_files/figure-html/unnamed-chunk-18-1.png){width=100%}\n:::\n:::\n\n\n\n\nDie Hilfeseite von `rope` sagt uns:\n\n>   Compute the proportion of the HDI (default to the 89% HDI) of a posterior distribution that lies within a region of practical equivalence.\n\n\n\n\nWeiter steht dort:\n\n`rope(x, range = \"default\", ci = 0.95, ci_method = \"ETI\", verbose = TRUE, ...)`\n\n`ETI` steht für \"Equal Tail Interval\", das ist ein Perzentilintervall.\n\nZum Argument `range` ist zu lesen:\n\n>   ROPE's lower and higher bounds. Should be \"default\" or depending on the number of outcome variables a vector or a list. In models with one response, range should be a vector of length two (e.g., c(-0.1, 0.1)). In multivariate models, range should be a list with a numeric vectors for each response variable. Vector names should correspond to the name of the response variables. If \"default\" and input is a vector, the range is set to c(-0.1, 0.1). If \"default\" and input is a Bayesian model, rope_range() is used.\n\n\nUnd `rope_range()` sagt uns in der Hilfeseite:\n\n>   Kruschke (2018) suggests that the region of practical equivalence could be set, by default, to a range from -0.1 to 0.1 of a standardized parameter (negligible effect size according to Cohen, 1988).\n\n\n\n\nWobei man schon im Methodenteil ROPE definieren sollte, dann müsste man das hier nicht mehr tun.\n\n\nMerkhilfe zur Entscheidung mit ROPE:\n\n\n>   Schneidet ROPE mit dem Berg, dem roten, dann Verwerfen ist verboten!\n\n\nMit \"Verwerfen\" ist das Verwerfen der \"Praktischnullhypothese\" gemeint.\n\nDas ROPE ist eine nette Sache: Man kann eine \"Praktischnullhypothese\" testen. \n*Besser* ist aber die Schätzung eines Konfidenzintervalls: Es beinhaltet\ndie Informationen eines ROPE aber noch mehr.\n\n\n####  Effektstärke\n\n\n\n\n\nWeiter macht es Sinn zu überlegen, ob Sie den Effekt für \"klein\" oder \"groß\" halten.\nDas ist eine subjektive Frage, die Sie am besten auf Basis theoretischer (nicht statistischer) Überlegungen\nentscheiden.\nAm besten Sie erwähnen im Methodenteil, was Sie als \"kleinen\" und \"großen\" Effekt einschätzen.\nSo könnten Sie argumentieren (auf Basis theoretischer Überlegungen), dass ein Unterschied von 1 Meile \"klein\" ist und 5 Meilen \"groß\".\nDemnach sprechen die Ergebnisse von `m1` deutlich gegen einen kleinen Effekt und sind gut mit einem \"großen\" Effekt kompatibel.\n\n\nVergleicht man Gruppen und ist z.B. die AV wenig anschaulich (etwa ein Summenscore),\nso bietet es sich, standardisierte Maße des Gruppenunterschieds anzugeben.\nMan nennt sie auch Maße der Effektstärke.\n\nBei Gruppenvergleichen ist *Cohens d* ein bekanntes Maß.\nMan kann es sich so ausgeben lassen:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(easystats)\ncohens_d(mpg ~ am, data = mtcars) %>% print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Cohen's d |        95% CI |\n|:---------|:--------------|\n|-1.48     |[-2.27, -0.67] |\nEstimated using pooled SD.\n\n\n:::\n:::\n\n\n\n\nMan gibt also die Regressionsformel und die Daten an.\nZu beachten ist, \ndass die AV zweistufig sein muss, sonst ist Cohens *d* nicht definiert.\n\nPraktischerweise kann man sich die Effektstärke auch gleich interpretieren lassen:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninterpret_cohens_d(-1.48)\n## [1] \"large\"\n## (Rules: cohen1988)\n```\n:::\n\n\n\n\n\nUm $R^2$ in einem Bayes-Modell zu bekommen, bietet sich die Funktion `bayes_R2()` an: \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1_R2 <- \n  bayes_R2(m1) %>% \n  as_tibble()\n\nhdi(m1_R2) %>% print_md()\n```\n\n::: {.cell-output-display}\n\n\nTable: Highest Density Interval\n\n|Parameter |     95% HDI |\n|:---------|:------------|\n|value     |[0.10, 0.54] |\n\n\n:::\n:::\n\n\n\n\n\n\n## Tipps\n\n\n### Schauen Sie sich Bachelorarbeiten an\n\nIm Netz findet man eine Reihe von Abschlussarbeiten, auch aus der (Wirtschafts-/Medien-)Psychologie. In @sec-beispiele-projektarbeiten finden Sie Anregungen dazu.\n\n\n\n### Diagramme exportieren\n\nDiagramme, die Sie mit `ggplot` erstellt haben, können Sie z.B. mit dem Befehl [`ggsave`](https://ggplot2.tidyverse.org/reference/ggsave.html) in eine Datei speichern (z.B. im Format PNG oder PDF).\n\n\n\nInteressant könnte für Sie auch das Paket `qwraps2` sein, \ndas u.a. einen Formulierungsvorschlag erstellt,\nwie man Statistiken im Fließtext anführt.\nBetrachten wir ein Beispiel mit `mtcars`.\nSagen wir, wir möchten den mittleren Spritverbrauch berichten.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(qwraps2)\n\nmean_sd(mtcars$mpg)\n## [1] \"20.09 $\\\\pm$ 6.03\"\n```\n:::\n\n\n\n\nDas Zeichen `$\\\\pm$` steht für \"Plus-Minus\" ± (im Formelmodus).\nIn Word sollten Sie es händisch durch den Glyphen (das Zeichen) \"±\" ersetzen.^[In Markdown-Formaten mit Quarto etc. wird es automatisch ersetzt durch das Plus-Minus-Zeichen.]\n\n\n\n\n### R-Paket `report`\n\nVielleicht ist das R-Paket `report` für Sie nützlich. Ich bin nicht ganz sicher,\ndenn das Paket ist noch sehr neu und berichtet recht viel Informationen.\nAber vielleicht wollen Sie es ja mal ausprobieren.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(easystats)\n```\n:::\n\n\n\n\n`report` lieft z.B. eine Beschreibung der Stichprobe:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmtcars %>% \n  select(1:3) %>%  # hier nur die Variablen 1 bis 3, der Einfachheit halber\n  report()\n## The data contains 32 observations of the following 3 variables:\n## \n##   - mpg: n = 32, Mean = 20.09, SD = 6.03, Median = 19.20, MAD = 5.41, range:\n## [10.40, 33.90], Skewness = 0.67, Kurtosis = -0.02, 0 missing\n##   - cyl: n = 32, Mean = 6.19, SD = 1.79, Median = 6.00, MAD = 2.97, range: [4,\n## 8], Skewness = -0.19, Kurtosis = -1.76, 0 missing\n##   - disp: n = 32, Mean = 230.72, SD = 123.94, Median = 196.30, MAD = 140.48,\n## range: [71.10, 472], Skewness = 0.42, Kurtosis = -1.07, 0 missing\n```\n:::\n\n\n\n\nOder auch für (Bayes-)Regressionsmodelle:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreport(m1)\n## \n## SAMPLING FOR MODEL 'continuous' NOW (CHAIN 1).\n## Chain 1: \n## Chain 1: Gradient evaluation took 9.8e-05 seconds\n## Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.98 seconds.\n## Chain 1: Adjust your expectations accordingly!\n## Chain 1: \n## Chain 1: \n## Chain 1: Iteration:    1 / 2000 [  0%]  (Warmup)\n## Chain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)\n## Chain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)\n## Chain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)\n## Chain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)\n## Chain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)\n## Chain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)\n## Chain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)\n## Chain 1: Iteration: 1400 / 2000 [ 70%]  (Sampling)\n## Chain 1: Iteration: 1600 / 2000 [ 80%]  (Sampling)\n## Chain 1: Iteration: 1800 / 2000 [ 90%]  (Sampling)\n## Chain 1: Iteration: 2000 / 2000 [100%]  (Sampling)\n## Chain 1: \n## Chain 1:  Elapsed Time: 0.038 seconds (Warm-up)\n## Chain 1:                0.038 seconds (Sampling)\n## Chain 1:                0.076 seconds (Total)\n## Chain 1: \n## \n## SAMPLING FOR MODEL 'continuous' NOW (CHAIN 2).\n## Chain 2: \n## Chain 2: Gradient evaluation took 1.3e-05 seconds\n## Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 0.13 seconds.\n## Chain 2: Adjust your expectations accordingly!\n## Chain 2: \n## Chain 2: \n## Chain 2: Iteration:    1 / 2000 [  0%]  (Warmup)\n## Chain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)\n## Chain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)\n## Chain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)\n## Chain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)\n## Chain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)\n## Chain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)\n## Chain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)\n## Chain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)\n## Chain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)\n## Chain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)\n## Chain 2: Iteration: 2000 / 2000 [100%]  (Sampling)\n## Chain 2: \n## Chain 2:  Elapsed Time: 0.044 seconds (Warm-up)\n## Chain 2:                0.047 seconds (Sampling)\n## Chain 2:                0.091 seconds (Total)\n## Chain 2: \n## \n## SAMPLING FOR MODEL 'continuous' NOW (CHAIN 3).\n## Chain 3: \n## Chain 3: Gradient evaluation took 1.8e-05 seconds\n## Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 0.18 seconds.\n## Chain 3: Adjust your expectations accordingly!\n## Chain 3: \n## Chain 3: \n## Chain 3: Iteration:    1 / 2000 [  0%]  (Warmup)\n## Chain 3: Iteration:  200 / 2000 [ 10%]  (Warmup)\n## Chain 3: Iteration:  400 / 2000 [ 20%]  (Warmup)\n## Chain 3: Iteration:  600 / 2000 [ 30%]  (Warmup)\n## Chain 3: Iteration:  800 / 2000 [ 40%]  (Warmup)\n## Chain 3: Iteration: 1000 / 2000 [ 50%]  (Warmup)\n## Chain 3: Iteration: 1001 / 2000 [ 50%]  (Sampling)\n## Chain 3: Iteration: 1200 / 2000 [ 60%]  (Sampling)\n## Chain 3: Iteration: 1400 / 2000 [ 70%]  (Sampling)\n## Chain 3: Iteration: 1600 / 2000 [ 80%]  (Sampling)\n## Chain 3: Iteration: 1800 / 2000 [ 90%]  (Sampling)\n## Chain 3: Iteration: 2000 / 2000 [100%]  (Sampling)\n## Chain 3: \n## Chain 3:  Elapsed Time: 0.043 seconds (Warm-up)\n## Chain 3:                0.04 seconds (Sampling)\n## Chain 3:                0.083 seconds (Total)\n## Chain 3: \n## \n## SAMPLING FOR MODEL 'continuous' NOW (CHAIN 4).\n## Chain 4: \n## Chain 4: Gradient evaluation took 1.4e-05 seconds\n## Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 0.14 seconds.\n## Chain 4: Adjust your expectations accordingly!\n## Chain 4: \n## Chain 4: \n## Chain 4: Iteration:    1 / 2000 [  0%]  (Warmup)\n## Chain 4: Iteration:  200 / 2000 [ 10%]  (Warmup)\n## Chain 4: Iteration:  400 / 2000 [ 20%]  (Warmup)\n## Chain 4: Iteration:  600 / 2000 [ 30%]  (Warmup)\n## Chain 4: Iteration:  800 / 2000 [ 40%]  (Warmup)\n## Chain 4: Iteration: 1000 / 2000 [ 50%]  (Warmup)\n## Chain 4: Iteration: 1001 / 2000 [ 50%]  (Sampling)\n## Chain 4: Iteration: 1200 / 2000 [ 60%]  (Sampling)\n## Chain 4: Iteration: 1400 / 2000 [ 70%]  (Sampling)\n## Chain 4: Iteration: 1600 / 2000 [ 80%]  (Sampling)\n## Chain 4: Iteration: 1800 / 2000 [ 90%]  (Sampling)\n## Chain 4: Iteration: 2000 / 2000 [100%]  (Sampling)\n## Chain 4: \n## Chain 4:  Elapsed Time: 0.035 seconds (Warm-up)\n## Chain 4:                0.042 seconds (Sampling)\n## Chain 4:                0.077 seconds (Total)\n## Chain 4:\n## We fitted a Bayesian linear model (estimated using MCMC sampling with 4 chains\n## of 2000 iterations and a warmup of 1000) to predict mpg with am (formula: mpg ~\n## am). Priors over parameters were set as normal (mean = 0.00, SD = 30.20)\n## distributions. The model's explanatory power is substantial (R2 = 0.35, 95% CI\n## [0.10, 0.54], adj. R2 = 0.29). The model's intercept, corresponding to am = 0,\n## is at 17.14 (95% CI [14.85, 19.51]). Within this model:\n## \n##   - The effect of am (Median = 7.21, 95% CI [3.72, 10.70]) has a 99.95%\n## probability of being positive (> 0), 99.92% of being significant (> 0.30), and\n## 99.72% of being large (> 1.81). The estimation successfully converged (Rhat =\n## 0.999) and the indices are reliable (ESS = 3755)\n## \n## Following the Sequential Effect eXistence and sIgnificance Testing (SEXIT)\n## framework, we report the median of the posterior distribution and its 95% CI\n## (Highest Density Interval), along the probability of direction (pd), the\n## probability of significance and the probability of being large. The thresholds\n## beyond which the effect is considered as significant (i.e., non-negligible) and\n## large are |0.30| and |1.81| (corresponding respectively to 0.05 and 0.30 of the\n## outcome's SD). Convergence and stability of the Bayesian sampling has been\n## assessed using R-hat, which should be below 1.01 (Vehtari et al., 2019), and\n## Effective Sample Size (ESS), which should be greater than 1000 (Burkner, 2017).\n```\n:::\n\n\n\n\n\n`report` berichtet Statistiken nach dem sog. SEXIT-Konzept @makowski_indices_2019.\nWenn Ihnen einige Statistiken nicht geläufig sind, ignorieren Sie sich einfach\noder lesen Sie sie nach.\n \n\n## Reproduzierbarkeit\n\n\nDer Geist der Wissenschaft heißt *Transparenz.*\nAlso machen Sie ihre Arbeit nachprüfbar und legen Sie die zentralen Schritte offen:\n\n- Reichen Sie die *Daten* ein; legen Sie ein *Data-Dictionary* (Codebook) bei.\n- Reichen Sie die *Syntax* ein.\n- Reichen Sie die *Messinstrumente* und *Stimuli* ein (sofern nicht öffentlich einsehbar).\n- Explizieren Sie Ihr Vorgehen *prägnant.*\n- Erläutern Sie Ihre theoretischen *Argumente* nachvollziehbar und unter Bezug auf die Literatur.\n- Fixieren Sie die *Zufallszahlen* in Analysen, die mit Zufallszahlen arbeiten (z.B. `stan_glm`).\n\nDie Zufallszahlen in `stan_glm` können Sie z.B. so fixieren:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- stan_glm(av ~ uv, data = meine_daten, seed = 42)\n```\n:::\n\n\n\n\n\nDie genaue Wert bei `seed` ist nicht entscheidend;\naber ein *bestimmter*  Seed-Wert wird immer die gleichen Zufallszahlen zielen und damit immer die gleichen Parameterwerte im Modell nach sich ziehen.\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}