# Abschluss


## Beispiele für gute Projektarbeiten {#sec-beispiele-projektarbeiten}


Auf der Seite der [Schriftenreihe des Instituts für Wirtschaftspsychologie (iwp) der FOM Hochschule](https://forschung.fom.de/forschung/institute/iwp/publikationen.html#!acc=iwp-schriftenreihe/accid=18799) finden Sie eine Auswahl an insgesamt gut aufbereiteten Berichten zu psychologischen Studien -- fast alle aus studentischer Feder.
Diese Arbeiten können als Vorbilder für Ihren eigenen Bericht dienen.


Interessant ist z.B. die Arbeit zum Thema [Selbstwirksamkeit, Selbstregulation und Prokrastination – Überprüfung eines Mediationsmodells](https://forschung.fom.de/fileadmin/fom/forschung/iwp/Schriftenreihe/FOM-Forschung-iwp-Schriftenreihe-Band-11-Schuhmacher-Beatrice-Prokastination-2022.pdf) von @schuhmacher_selbstwirksamkeit_2022. Die Arbeit ist frei im Netz verfügbar.


:::{callout-tip}
Lernen Sie von anderen, vergleichbaren Arbeiten und nutzen Sie diese als Vorbild. $\square$
:::



## FAQ


### Sekundärzitate

FRAGE: In der von mir verwendeten Literatur wird häufig aus nochmal anderen Quellen zitiert. Allerdings passen diese Quellen nicht immer zu unserem Thema, sondern enthalten einen Inhalt, den ich gerne für meine Arbeit übernehmen würde, wenn überhaupt, nur recht nebensächlich, bzw. finde ich darin oft die Aussage, die ich gerne zitieren würde nicht wieder. Außerdem habe ich zu vielen dieser Arbeiten keinen Zugriff. Daher meine Frage, da ich das auch schon von anderen Studierenden aus anderen Universitäten gehört habe: Kann man z.B. schreiben: "Müller schreibt in seinem Artikel, dass Meier xyz herausgefunden hat." oder muss immer die Primärquelle angegeben werden. Und welchen Einfluss hätte das auf die Bewertung der Arbeit?

ANTWORT: Ja, man kann Sekundärzitate verwenden, es ist aber nicht empfehlenswert. Besser sind zwei Strategien: 1. Suchen Sie nach anderen Artikeln mit ähnlicher bzw. passender Aussage. Häufig gibt es mehrere Artikel zu einem Thema. 2. Erschließen Sie sich zusätzliche Wege für Volltexte, s. @sec-volltext.

### Schriftgröße

FRAGE: Bezüglich der Formatierung der Seminararbeit: In dem Buch "Schreiben und Gestalten von Abschlussarbeiten", das Sie uns empfohlen haben, steht Times New Roman in Schriftgröße 12 und mit einem Zeilenabstand von 1,5 als geeigneter Standard. In Ihrem Skript ist zwar ebenfalls eine Serifenschrift, allerdings in Schriftgröße 11 und mit einem Zeilenabstand von 1 - 1,2 vorgegeben. Woran sollte man sich denn eher orientieren?

ANTWORT: Beides ist in Ordnung, aber mir ist ein Zeilenabstand von 1 - 1.2 lieber als 1.5.


### Induktion von Einsamkeit

FRAGE: Ein weiterer wichtiger Punkt für uns ist die Frage, ob die Einsamkeit wirklich erfolgreich induziert wurde. Zum Beispiel: Wenn wir ein Modell rechnen mit „Anthropomorphismus“ als abhängiger Variable und „Musik“ und „Geschichte“ als unabhängige Variablen (Hypothese: Je einsamer Probanden sind (nach Geschichte + Musik), desto anthropomorpher nehmen sie den Roboter war), wie wissen wir dann, ob die Einsamkeit wirklich wirkt? Müssen wir vorher ein eigenes Regressionsmodell rechnen, z. B. mit „Loneliness“ aus Fragebogen F2 als AV und „einsame Geschichte“ als UV, um zu prüfen, ob die Induktion funktioniert hat?

ANTWORT: Eine gute Lösung wäre eine Mediatoranalyse. UV: `Ind`uktion von Einsamkeit (Musik/Geschichte); Mediator: Einsamkeit (`einsam`), AV: Anthropomorphe Wahrnehmnung (`anthro`). Also: `Ind -> einsam -> anthro`, d.h. `uv -> m -> av`. Das Thema haben wir nicht im Unterricht behandelt, so dass es ich es nicht erwarte (ich lasse mich aber positiv überraschen). Die nächstbeste Lösung ist, folgende Modelle zu prüfen: `uv -> av`, `uv -> m`, `m -> av` und jeweils auf "Signifikanz" zu prüfen.


### Können Sie uns einen Tipp geben?

FRAGE: Wir sind aktuell dabei unsere Datenauswertung auf R zu machen. Bisher haben wir das Datenjudo gemacht (Spalten mit fehlenden Werten entfernt, Items umkodiert, Items zu einem Konstrukt zusammengefasst und den Mittelwert gebildet, Korrelationen  angeschaut,..). Nun haben wir angefangen verschiedene Modelle zu erstellen und kommen nicht wirklich weiter. Wir sind uns aber sehr unsicher, wie wir die Ergebnisse nun interpretieren können. Wenn wir es richtig verstanden haben, kann keines der Modelle unsere  Hypothesen bestätigen. Können Sie uns einen Tipp geben, wie wir noch weiter verfahren können?

ANTWORT: Was Sie bisher gemacht haben, hört sich gut an. Tipps: 1. Setzen Sie die Analysen aus QM2 um, falls Sie das noch nicht gemacht haben. 2. Gehen Sie die Checkliste zur Datnanalyse durch, s. @sec-checkdaten. 3. Schauen Sie sich die Videos auf meinem [YouTube-Kanal](https://www.youtube.com/@sebastiansauerstatistics) an, besonders die Playlists aus @sec-bayesmod. 4. Prüfen Sie, ob Ihre (Regressions-)Modelle zu Ihren Hypothesen bzw. Forschungsfragen passen. 5. Schauen Sie sich die als empfehlenswert ausgestellten Arbeiten an (s. Moodle).



## Fertig

Sie haben dieses Modul abgeschlossen. 
Sie müssen Ihren Fortschritt im Projektplan nicht mehr im Blick behalten. 😄 
 
{{< fa award >}}                      
 
 
 






