project:
  type: book


filters:
  - search-replace
search-replace:
  z.B.  : "z.&thinsp;B."
  d.h.  : "d.&thinsp;h."
  +br    : <br>\newline

lang: de


book:
  title: "Forschungsprojekt"
  author:
    - name: Sebastian Sauer
      orcid: 0000-0003-1515-8348
  date: now
  doi: 10.5281/zenodo.6602668
  repo-url: https://github.com/sebastiansauer/fopra
  repo-actions: [source, issue]
  cover-image: img/foproa-logo.png
  #cover-image-alt: "Willkommen in Ihrem Forschungsprojekt!"
  favicon: img/fopra-logo-small.png
  license: CC-By
  sidebar:
    logo: img/fopra-logo-small.png
    search: true
  # google-analytics:


  chapters:
    - part: "Organisatorisches"
      chapters:
        - index.qmd

    - part: "Theorie"
      chapters:
        - 010-rahmen.qmd
        - 020-themawahl.qmd
        - 030-Schreiben.qmd
    - part: "Empirie"
      chapters:
        - 040-Populationsbeschreibung.qmd
        - 050-Explikation.qmd
        - 060-Messen.qmd
        - 070-Erheben.qmd
        - 075-kausal.qmd
        - 080-Auswerten.qmd
        - 085-aufbereiten.qmd
        - 090-Modellieren.qmd
    - part: "Fertigstellen"
      chapters:
        - 100-Statistiken-berichten.qmd
        - 120-abschluss.qmd
        - 130-references.qmd
      # - test.qmd

website:
  favicon: img/Albert_Einstein_head.jpg
  open-graph: true
  image: img/Albert_Einstein_head.jpg
  google-analytics: G-1K43PN7CP3
  cookie-consent: true


bibliography: library-ses.bib


editor: source
keep-md: false
prefer-html: true
code-annotations: hover

execute:
  freeze: auto
  warning: false
  cache: true


knitr:
  opts_knit:
    verbose: true
    fig-align: center
  opts_chunk:
    collapse: true
    # comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: false

format:
  html:
    toc: true
    theme:
      light: lumen
      dark: darkly
    css: styles.css
    number-sections: true
    df-print: paged
    code-fold: false
    fig-align: center
    code-link: true
    mermaid:
      theme: neutral
  # pdf:
  #   toc: true
  #   number-sections: true
  #   colorlinks: true
  #   keep-tex: true
  #   papersize: a4
  #   df-print: kable
  #   fig-align: center



