project:
  type: book


lang: de


book:
  title: "Forschungsprojekt"
  author: "Sebastian Sauer"
  date: now
  chapters:
    - index.qmd
    - 010-rahmen.qmd
    - 020-themawahl.qmd
    - 030-Schreiben.qmd
    - 040-Populationsbeschreibung.qmd
    - 050-Explikation.qmd
    - 060-Messen.qmd
    - 070-Erheben.qmd
    - 075-kausal.qmd
    - 080-Auswerten.qmd
    - 090-Modellieren.qmd
    - 100-Statistiken-berichten.qmd
    - 110-pruefung.qmd
    - 120-abschluss.qmd
    - 130-references.qmd
    # - test.qmd


bibliography:  /Users/sebastiansaueruser/Google Drive/Literatur/refmgt/library-ses.bib


editor: source
keep-md: false
prefer-html: true

execute:
  freeze: auto
  warning: false
  cache: true

knitr:
  opts_knit:
    verbose: true
    fig-align: center
  opts_chunk:
    collapse: true
    # comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: false

format:
  html:
    toc: true
    theme: lumen
    css: styles.css
    number-sections: true
    df-print: paged
    code-fold: false
    fig-align: center
    code-link: true
    mermaid:
      theme: neutral
  # pdf:
  #   toc: true
  #   number-sections: true
  #   colorlinks: true
  #   keep-tex: true
  #   papersize: a4
  #   df-print: kable
  #   fig-align: center



