---
title: "Quiz: Daten aufbereiten"
output: exams2forms::webquiz
---

```{r exams2forms-setup, include = FALSE}
## package and exercises
library("exams2forms")
exm <- c("/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/085-aufbereiten/across-schleife-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/085-aufbereiten/bind-rows-cols-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/085-aufbereiten/case-when-itemlabels-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/085-aufbereiten/dubletten-distinct-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/085-aufbereiten/join-key-spalte-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/085-aufbereiten/parse-number-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/085-aufbereiten/spaltennamen-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/085-aufbereiten/summenscore-vs-mittelwertscore-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/085-aufbereiten/umpolen-rechenregel-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/085-aufbereiten/z-standardisierung-schoice.Rmd"
)
```

```{r exams2forms-include, echo = FALSE, message = FALSE, results="asis"}
exams2forms(exm,  n = 1L, nsamp = NULL)
```
