---
title: "Quiz: Explikation"
output: exams2forms::webquiz
---

```{r exams2forms-setup, include = FALSE}
## package and exercises
library("exams2forms")
exm <- c("/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/050-Explikation/ave-berechnung-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/050-Explikation/between-within-subject-design-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/050-Explikation/explikation-definition-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/050-Explikation/interne-vs-externe-validitaet-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/050-Explikation/interventionsstudie-beobachtungsstudie-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/050-Explikation/max-kon-min-prinzip-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/050-Explikation/mill-kausalitaetsbedingungen-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/050-Explikation/randomisierung-funktion-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/050-Explikation/stoervariable-kontrollvariable-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/050-Explikation/zurmo-determinanten-schoice.Rmd"
)
```

```{r exams2forms-include, echo = FALSE, message = FALSE, results="asis"}
exams2forms(exm,  n = 1L, nsamp = NULL)
```
