---
title: "Quiz: Modellieren"
output: exams2forms::webquiz
---

```{r exams2forms-setup, include = FALSE}
## package and exercises
library("exams2forms")
exm <- c("/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/090-Modellieren/index-moderierte-mediation-rechnung-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/090-Modellieren/inferenzstatistik-definition-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/090-Modellieren/konfidenzintervall-nullhypothese-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/090-Modellieren/mediationsanalyse-effektzerlegung-rechnung-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/090-Modellieren/modellformel-uv-auswahl-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/090-Modellieren/probability-of-direction-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/090-Modellieren/r-quadrat-effektstaerke-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/090-Modellieren/random-intercept-modell-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/090-Modellieren/rope-interpretation-schoice.Rmd", 
"/home/sebastian-sauer/Dokumente/3X_Lehre/36_Lehre-Entwicklung/08_fopra/quiz/090-Modellieren/vorher-nachher-messung-vorteil-schoice.Rmd"
)
```

```{r exams2forms-include, echo = FALSE, message = FALSE, results="asis"}
exams2forms(exm,  n = 1L, nsamp = NULL)
```
