flowchart LR
  subgraph R[Rahmen]
    direction LR
    subgraph V[Theorie]
      direction TB
      E[Themawahl] --> Um[Hypothesen]
    end
    subgraph M[Empirie]
      direction TB
      M1[Studiendesign] --> Vis[Messinstrumente]
      Vis --> U[Stichprobe]
      U --> G[Auswertung]
    end
    subgraph N[Fertigstellen]
      direction TB
      D[Diskutieren]
    end
  V --> M
  M --> N
  end
