
---
subtitle: "Forschungspraktikum in Psychologie"
title: "Laufende Studien, SoSe 22"
author: "Sebastian Sauer"
date: "Letzte Aktualisierung: `r Sys.time()`"
output:
   
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    number_sections: TRUE
editor_options: 
  chunk_output_type: console
---

```{r global-knitr-options, include=FALSE}
  knitr::opts_chunk$set(
  fig.pos = 'H',
  fig.asp = 0.618,
  fig.align='center',
  fig.width = 5,
  out.width = "100%",
  fig.cap = "", 
  fig.path = "chunk-img/",
  dpi = 300,
  # tidy = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  cache = FALSE,
  fig.show = "hold")
```




# Hos & Vursavas


Liebe Studierende,

wir sind AWM- Studierende aus dem 4. Semester und beschäftigen uns im Rahmen unseres Forschungsprojektes mit dem Thema psychisches Wohlbefinden und Achtsamkeit bei jungen Erwachsenen.

Wie zu entnehmen ist, sind junge Erwachsene unsere Zielgruppe. Hier kommen Sie ins Spiel: Sie sind gefragt!! :-)

Das Experiment wird in den Räumlichkeiten der Hochschule Ansbach oder über Zoom stattfinden. Da wir wissen, dass ein Experiment mit Aufwand verbunden ist, verlosen wir unter allen Teilnehmern an insgesamt drei Personen jeweils einen 15€ Amazon Gutschein, 5€ Spotify Gutschein sowie eine Tafel Schokolade.
Falls Interesse an der Studie besteht, würden wir Sie bitten sich in der Google Umfrage einzutragen.
https://forms.gle/dPMos8SscBrBgHbx7

Bei weiteren Fragen zur Studie schreiben Sie uns gerne eine E-Mail.

Buket Hos: b.hos16255@hs-ansbach.de

Sarah Vursavas: s.vursavas17161@hs-ansbach.de






# Eva, Christiné, Sabrina, Fabian, Klara | AWM 

Studie Feedbackakzeptanz - Arbeitnehmer aufgepasst! 


Wir beforschen Feedback-Akzeptanz in der Personalführung und

unsere Zielgruppe sind hierfür Arbeitnehmende bzw. Leute die schon berufstätig sind.
Wir würden uns sehr freuen, wenn Sie / Ihr euch Zeit nehmen würdet, um unseren Fragebogen auszufüllen, die Dauer dafür beträgt ca. 7 Minuten.




Alle weiteren Infos finden Sie/ Ihr auf der Landingpage.




Link zum Fragebogen:
https://www.soscisurvey.de/HSstudy/


Besten Dank für die Teilnahme

Eva, Christiné, Sabrina, Fabian, Klara | AWM 





# Alles für die Wissenschaft



**Hey DU**

Du  wolltest schon immer bei einer Studie mitmachen und Deine kognitiven Fähigkeiten unter Beweis stellen. Dann bist  Du für unsere Studie genau der/die Richtige.




DU BIST

- zwischen 18 und 42 Jahre alt




- bereit an die Hochschule Ansbach zu kommen




- an der Wissenschaft interessiert und willst deine kognitiven Fähigkeiten beweisen




- motiviert einen Amazon Gutschein
 zu gewinnen?




- Wann
 / Wo?

- 21.05.22
 um 12:00-14:00 Uhr / Hochschule Ansbach Räume 92.1.14 und 92.1.17



- Wenn
 Du Fragen hast, dann melde Dich doch einfach über Instagram oder per Mail (teamslowmedia@gmail.com)
 bei uns. 

- Wenn
 wir Dich jetzt schon überzeugen konnten, dann trage Dich in unsere Liste ein und hilf uns dabei, eine spannende und erkenntnisreiche Studie durchzuführen. 

https://docs.google.com/forms/d/1HzuDiJe0NiJCeAOjrVzpGRF9lWptsjadJ8O7VpkF3ng/edit


# Jannis, Lukas, Annkathrin, Stella, Carina und Nils  | Research Project - AWM
 
Hey,

im Rahmen unserer studentischen Arbeit zu dem Thema Konsumverhalten 🥩👗⚽ würden wir uns freuen, wenn Du Dir 10 Minuten Zeit nehmen würdest uns zu unterstützen. 
Als kleine Motivationsspritze 💉 kannst Du einen AMAZON-GUTSCHEIN gewinnen!💰
Wenn Dir der Fragebogen gefallen hat, würden wir uns freuen, wenn Du diesen Fragebogen an Deine Freunde und Bekannte weiterleiten würdest. 

https://www.soscisurvey.de/QNR-SCL-SS22-4/

Vielen Dank für Deine Teilnahme an unserer Studie.🤓





# Startseite


[Startseite](https://sebastiansauer.github.io/fopra/)
