---
subtitle: "Forschungspraktikum in Psychologie"
title: "Lernziele des Moduls"
author: "Sebastian Sauer"
date: "Letzte Aktualisierung: `r Sys.time()`"
output:
   
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    number_sections: TRUE
editor_options: 
  chunk_output_type: console
---

```{r global-knitr-options, include=FALSE}
  knitr::opts_chunk$set(
  fig.pos = 'H',
  fig.asp = 0.618,
  fig.align='center',
  fig.width = 5,
  out.width = "100%",
  fig.cap = "", 
  fig.path = "chunk-img/",
  dpi = 300,
  # tidy = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  cache = FALSE,
  fig.show = "hold")
```


</br>
</br>
</br>



- Die Studentis können eigenständig einige Arten von quantitativen psychologischen Studien in allen wesentlichen Schritten planen, erheben, auswerten, interpretieren und zusammenschreiben.
    - Im Hinblick auf *Versuchsplanung* können die Studentis Versuchspläne passend zu ihrer Forschungsfrage auswählen und kritisch bewerten; darüber hinaus können Sie Fallzahlen vorab planen.
    - Im Hinblick auf *Datenerhebung* können die Studentis für ihre Forschungsfrage passende Messinstrumente auswählen. Zentrale rechtliche und ethische Aspekte sind ihnen bekannt. Softwarelösungen zur Datenerhebung können sie auswählen und einsetzen. Probleme und Lösungen im Hinblick auf Störvariablen können sie diskutieren.
    - Im Hinblick auf *Datenauswertung* können die Studentis die Verfahren aus den Modulen QM1 und QM2 praktisch auf ihre eigenen Daten anwenden.
    - Im Hinblick auf *Interpretation* von Versuchsergebnissen wissen die Studentis um die Grenzen der internen und externen Validität bestimmter Versuchspläne, von Störfaktoren und “Researchers’ Degrees of Freedom”.
    - Im Hinblick auf die *Berichtlegung* von Studienergebnissen sind die Studentis in der Lage, die Methoden aus dem Modul Wissenschaftliches Arbeiten auf ihre eigene Studie hin anzuwenden.
- Die Studentis können quantitative psychologische Studien auf ihre Güte hin kritisch untersuchen.








# Startseite


[Startseite](https://sebastiansauer.github.io/fopra/)
