---
subtitle: "Forschungspraktikum in Psychologie"
title: "Modulverlauf"
author: "Sebastian Sauer"
date: "Letzte Aktualisierung: `r Sys.time()`"
output:
   
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    number_sections: TRUE
editor_options: 
  chunk_output_type: console
---

```{r global-knitr-options, include=FALSE}
  knitr::opts_chunk$set(
  fig.pos = 'H',
  fig.asp = 0.618,
  fig.align='center',
  fig.width = 5,
  out.width = "100%",
  fig.cap = "", 
  fig.path = "chunk-img/",
  dpi = 300,
  # tidy = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  cache = FALSE,
  fig.show = "hold")
```



```{r}
library(yaml)
library(tidyverse)
library(glue)
```


</br>
</br>

Beachten Sie die Feiertage und die zusätzlichen lehrfreien Tage.
Auf der Homepage der Hochschule finden Sie eine Liste dazu.

</br>
</br>




```{r build-table, results='asis', echo=FALSE}
modul_zsfg <- yaml::read_yaml(paste0(here::here(), "/Interna/modul-zsfg.yaml"))


titel_nr <- modul_zsfg %>% names() %>% seq_along()


datum <- vector()
thema <- vector()
kw <- vector()

for (i in titel_nr){
  datum[i] <- modul_zsfg[[i]][["datum"]]
  kw[i] <- modul_zsfg[[i]][["kw"]]
  thema[i] <- modul_zsfg[[i]][["title"]]
}


cat("Nr. | Kalenderwoche | Datum | Thema")
cat("\n")
cat("---|---|---|--")
cat("\n")

for (j in titel_nr){
  cat(glue("{titel_nr[j]} | {kw[j]} | {datum[j]} | {thema[j]}"))
  cat("\n")
  #cat("---|---|---|--")
  #cat("\n")
}
```








