---
subtitle: "Forschungspraktikum in Psychologie"
title: "Themen im Überblick"
author: "Sebastian Sauer"
date: "Letzte Aktualisierung: `r Sys.time()`"
output:
   
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    number_sections: TRUE
editor_options: 
  chunk_output_type: console
---

```{r global-knitr-options, include=FALSE}
  knitr::opts_chunk$set(
  fig.pos = 'H',
  fig.asp = 0.618,
  fig.align='center',
  fig.width = 5,
  out.width = "100%",
  fig.cap = "", 
  fig.path = "chunk-img/",
  dpi = 300,
  # tidy = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  cache = FALSE,
  fig.show = "hold")
```



```{r}
#library(yaml)
library(tidyverse)
#library(glue)
```



</br>
</br>




# Themen

```{r build-themen, child="Interna/build-themen.Rmd", results='asis', echo=FALSE}
```



# Modulverlauf





```{r source-timetable, echo = FALSE, cache=FALSE}
timetable_file <- "Interna/Modulverlauf.xlsx"
stopifnot(file.exists(timetable_file))
timetable <- readxl::read_xlsx(timetable_file)

gt::gt(timetable) |> 
  gt::cols_width(
    1 ~ gt::pct(5),
    2 ~ gt::pct(20),
    3 ~ gt::pct(20),
    4 ~ gt::pct(45)
  )
```




# Startseite


[Startseite](https://sebastiansauer.github.io/fopra/)


